"""
Fetches top stories from Hacker News using the HN Firebase API (https://hacker-news.firebaseio.com/v0). Gets story IDs from topstories.json then fetches each item. Returns title, url, score, author.

Auto-generated by LearnNewAgent on 2026-03-13 20:51.
"""

import json
import urllib.request
from openrappter.agents.basic_agent import BasicAgent


class HackerNewsAgent(BasicAgent):
    def __init__(self):
        self.name = 'HackerNews'
        self.metadata = {
            "name": self.name,
            "description": "Fetches top stories from Hacker News using the HN Firebase API (https://hacker-news.firebaseio.com/v0). Gets story IDs from topstories.json then fetches each item. Returns title, url, score, author.",
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "The user's request or input."
                    },
                    "url": {
                        "type": "string",
                        "description": "URL to access."
                    }
                },
                "required": []
            }
        }
        super().__init__(name=self.name, metadata=self.metadata)
    
    def perform(self, **kwargs):
        """Execute the agent's task."""
        query = kwargs.get('query', '')
        
        try:
            import requests

            base_url = "https://hacker-news.firebaseio.com/v0/"
            top_stories_url = f"{base_url}topstories.json"
            story_url = lambda story_id: f"{base_url}item/{story_id}.json"

            response = requests.get(top_stories_url)
            response.raise_for_status()
            top_story_ids = response.json()[:10]

            stories = []
            for story_id in top_story_ids:
                story_response = requests.get(story_url(story_id))
                story_response.raise_for_status()
                story_data = story_response.json()
                if story_data:
                    stories.append({
                        "title": story_data.get("title"),
                        "url": story_data.get("url"),
                        "score": story_data.get("score"),
                        "author": story_data.get("by")
                    })

            return json.dumps({"status": "success", "stories": stories})
        except Exception as e:
            return json.dumps({"status": "error", "message": str(e)})
