#!/usr/bin/env bash
#
# gen_soul_hashes.sh — regenerate rapp_brainstem/tests/soul_defaults.sha256
#
# Walks the full git history of rapp_brainstem/soul.md and records the NORMALIZED
# SHA-256 (see rapp_brainstem/tests/soul_hash.py) of every default soul the project
# has ever shipped, plus the current working-tree default. install.sh / install.ps1
# consult this manifest on upgrade: if an installed soul.md normalizes to one of
# these hashes it is an unmodified historical default and is safe to refresh; any
# other soul is a user customization and is preserved untouched.
#
# Run this whenever rapp_brainstem/soul.md changes — a pytest in
# test_local_agents.py fails CI if the manifest is stale:
#
#   bash tests/gen_soul_hashes.sh
#
# Deterministic: output is sorted, so re-running with no soul change is a no-op diff.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SOUL_REL="rapp_brainstem/soul.md"
HASHER="$REPO_ROOT/rapp_brainstem/tests/soul_hash.py"
OUT="$REPO_ROOT/rapp_brainstem/tests/soul_defaults.sha256"
PY="${PYTHON:-python3}"

cd "$REPO_ROOT"

hash_stream() { "$PY" "$HASHER" -; }

rows="$(mktemp)"
trap 'rm -f "$rows"' EXIT

emit() { printf '%s\t%s\n' "$1" "$2" >> "$rows"; }

while IFS= read -r commit; do
    [ -n "$commit" ] || continue
    path="$SOUL_REL"
    if ! git cat-file -e "$commit:$path" 2>/dev/null; then
        path="$(git ls-tree -r --name-only "$commit" | grep -E '(^|/)soul\.md$' | grep -m1 rapp_brainstem || true)"
    fi
    [ -n "$path" ] || continue
    hash="$(git show "$commit:$path" 2>/dev/null | hash_stream || true)"
    [ -n "$hash" ] || continue
    emit "$hash" "$(git log -1 --format='%h %s' "$commit")"
done < <(git log --follow --format='%H' -- "$SOUL_REL")

if [ -f "$REPO_ROOT/$SOUL_REL" ]; then
    emit "$(hash_stream < "$REPO_ROOT/$SOUL_REL")" "current working tree ($SOUL_REL)"
fi

{
    echo "# soul_defaults.sha256 — normalized SHA-256 of every default soul.md ever shipped."
    echo "#"
    echo "# GENERATED by tests/gen_soul_hashes.sh — do not hand-edit. Regenerate after any"
    echo "# change to rapp_brainstem/soul.md (test_local_agents.py enforces this in CI)."
    echo "#"
    echo "# Normalization (rapp_brainstem/tests/soul_hash.py, mirrored natively in install.ps1):"
    echo "#   strip UTF-8 BOM; CRLF->LF; strip trailing space/tab per line; exactly one"
    echo "#   trailing newline; then sha256 (lowercase hex)."
    echo "#"
    echo "# On upgrade the installers refresh soul.md ONLY if its normalized hash is listed"
    echo "# here (an unmodified historical default) AND differs from the new default. Any"
    echo "# other soul — or one that cannot be normalized — is preserved byte-for-byte."
    echo "#"
    echo "# Format: <64-hex normalized sha256>  # <representative commit>"
    awk -F'\t' '!seen[$1]++ { printf "%s  # %s\n", $1, $2 }' "$rows" | sort
} > "$OUT"

echo "Wrote $OUT ($(grep -cE '^[0-9a-f]{64}' "$OUT" || true) unique default hashes)"
