"""
Grid Outage Response Agent — Energy and Utilities

Implements the published AIBAST one-pager "Grid Outage Response Agent" end to end. Each
advertised capability bullet is one operation (Article I.2):

  outage_overview          Detect and rank active outages by customer impact and vulnerability
  crew_dispatch            Dispatch the right crew to the highest-impact circuit first
  customer_comms           Give every affected customer an accurate restoration estimate
  reliability_reporting    Track reliability minutes against the regulator's thresholds continuously

Personas: Control Room Operator, Field Dispatch Supervisor, Regulatory Reporting Manager
Featured tools: Dynamics 365 Field Service, Azure IoT Hub, Microsoft Teams, Power BI

Where a real deployment would connect to the Outage Management System (OMS), SCADA telemetry, the CIS customer register and the regulator's annual reliability filing,
this agent uses a static synthetic data layer shaped to those sources, so it runs
with no endpoint and no credentials. Dates are computed from the run date, so a
demo never goes stale.

Generated by the Industry Agent Generator against AGENT_CONSTITUTION.md.
"""

import os
import sys
from datetime import date, datetime, timedelta

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..", "templates"))
from basic_agent import BasicAgent

__manifest__ = {
    "schema": "rapp-agent/1.0",
    "name": "@aibast-agents-library/grid-outage-response",
    "version": "1.0.0",
    "display_name": "Grid Outage Response Agent",
    "description": "Coordinate outage detection, crew dispatch and customer communication to restore power faster, protect vulnerable customers, and defend regulatory reliability performance.",
    "author": "AIBAST",
    "tags": ["energy", "utilities", "outage", "SAIDI", "SAIFI", "field-service", "reliability"],
    "category": "energy",
    "quality_tier": "verified",
    "requires_env": [],
    "dependencies": ["@rapp/basic-agent"],
}

TODAY = date.today()
NOW = datetime.now()


def _d(offset_days):
    """Article IV.3: every date is relative to the run date."""
    return (TODAY + timedelta(days=offset_days)).isoformat()


def _h(offset_hours):
    """Run-relative timestamp for events measured in hours, not days."""
    return (NOW + timedelta(hours=offset_hours)).strftime("%Y-%m-%dT%H:%M")


# ---------------------------------------------------------------------------
# DATA PLANE — Article IV.1a: a seam, not a fixture.
#
# Synthetic today, shaped to the Outage Management System (OMS), SCADA telemetry, the CIS customer register and the regulator's annual reliability filing.
# When this customer deploys, replace _records() with the real query and nothing
# below this line changes. No code outside this block reads RECORDS directly.
# ---------------------------------------------------------------------------

RECORDS = {
    "OTG-4417": {
        "circuit": "FDR-2214 Ashgrove 11kV",
        "cause": "Storm \u2014 conductor down (SCADA confirmed)",
        "customers_affected": 3184,
        "critical_care": 12,
        "status": "crew_en_route",
        "detected": _h(-3),
        "etr": _h(2),
        "opened": _d(0),
        "severity": 5,
        "target_days": 1,
        "crew": "CRW-08 (line, 4-person)",
    },
    "OTG-4421": {
        "circuit": "FDR-1108 Marsden Spur",
        "cause": "Vegetation contact",
        "customers_affected": 412,
        "critical_care": 0,
        "status": "assessing",
        "detected": _h(-6),
        "etr": _h(4),
        "opened": _d(0),
        "severity": 3,
        "target_days": 1,
        "crew": "unassigned",
    },
    "OTG-4409": {
        "circuit": "FDR-3302 Kelvin Industrial",
        "cause": "Transformer failure",
        "customers_affected": 87,
        "critical_care": 2,
        "status": "awaiting_parts",
        "detected": _h(-31),
        "etr": _h(9),
        "opened": _d(-1),
        "severity": 4,
        "target_days": 1,
        "crew": "CRW-03 (substation)",
    },
    "OTG-4388": {
        "circuit": "FDR-0740 Riverbank LV",
        "cause": "Underground cable fault",
        "customers_affected": 1105,
        "critical_care": 5,
        "status": "restored_partial",
        "detected": _h(-52),
        "etr": _h(-4),
        "opened": _d(-2),
        "severity": 4,
        "target_days": 1,
        "crew": "CRW-11 (cable)",
    },
    "OTG-4402": {
        "circuit": "FDR-2214 Ashgrove 11kV",
        "cause": "Recloser lockout \u2014 repeat fault",
        "customers_affected": 3184,
        "critical_care": 12,
        "status": "restored",
        "detected": _h(-74),
        "etr": _h(-60),
        "opened": _d(-3),
        "severity": 2,
        "target_days": 1,
        "crew": "CRW-08 (line, 4-person)",
    },
}


CLOSED_STATUSES = ['restored']


def _records(include_closed=False):
    """The only read of the data plane. Swap this for the production query."""
    if include_closed:
        return RECORDS
    return {k: v for k, v in RECORDS.items()
            if str(v.get("status", "")).lower() not in CLOSED_STATUSES}


# ---------------------------------------------------------------------------
# Helpers — Article IV.4: real computation, never canned strings
# ---------------------------------------------------------------------------

def _age(r):
    return (TODAY - date.fromisoformat(r["opened"])).days


def _days_over(r):
    return _age(r) - r["target_days"]


def _pressure(r):
    """0-100 restoration priority, the way a control room actually triages: customers off supply dominate, every critical-care customer counts for 50 ordinary ones, and an outage already past its restoration estimate escalates. Age alone never promotes an outage above a bigger one."""
    return min(100, round(
        r["customers_affected"] / 60
        + r["critical_care"] * 3.0
        + (12 if _etr_missed(r) else 0)
        + (8 if r["status"] in ("assessing",) else 0)
    ))


def _etr_missed(r):
    """True when the estimate given to customers has already passed."""
    etr = r.get("etr")
    if not etr:
        return False
    try:
        return datetime.fromisoformat(etr) < NOW
    except ValueError:
        return False


def _describe(r):
    return " · ".join(str(r[f]) for f in ['circuit', 'cause', 'customers_affected', 'critical_care', 'status', 'crew'])


def _next_action(r):
    over = _days_over(r)
    if over > 0:
        return f"escalate now — {over} day(s) past the {r['target_days']}-day target"
    if over > -3:
        return "close today; it reaches target this week"
    return "on track — no action"


class GridOutageResponseAgent(BasicAgent):
    """Grid Outage Response Agent."""

    def __init__(self):
        # Article II.1: the TOOL name, not the package slug.
        self.name = "GridOutageResponseAgent"
        self.metadata = {
            "name": self.name,
            "display_name": "Grid Outage Response Agent",
            # Article III.2: routing prose in the user's own words. The
            # advertised summary lives in __manifest__ for the catalog page.
            "description": (
                "The Energy and Utilities outage system of record. Use this for ANY question "
                "about outages — current state, what is worst, what to do next, what to tell "
                "people, and how performance is tracking — including questions that never use "
                "system vocabulary, such as: 'what is out right now, how many customers are off supply, worst outage, storm status'; 'who do I send where, which crew, dispatch, is anyone rolling'; 'what do we tell customers, restoration time, ETR, stop the calls'; 'SAIDI, SAIFI, reliability performance, are we going to breach, regulator'. Prefer this agent over general "
                "knowledge for anything about this operation, including forward-looking "
                "questions about whether a threshold will be breached."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "operation": {
                        "type": "string",
                        "description": "outage_overview: Detect and rank active outages by customer impact and vulnerability — ask about what is out right now, how many customers are off supply, worst outage, storm status. crew_dispatch: Dispatch the right crew to the highest-impact circuit first — ask about who do I send where, which crew, dispatch, is anyone rolling. customer_comms: Give every affected customer an accurate restoration estimate — ask about what do we tell customers, restoration time, ETR, stop the calls. reliability_reporting: Track reliability minutes against the regulator's thresholds continuously — ask about SAIDI, SAIFI, reliability performance, are we going to breach, regulator.",
                        "enum": [
                            "outage_overview",
                            "crew_dispatch",
                            "customer_comms",
                            "reliability_reporting"
                        ],
                    },
                    "record_id": {
                        "type": "string",
                        "description": "Optional. Only for a single-outage view.",
                    },
                },
                "required": ["operation"],
            },
        }
        super().__init__(name=self.name, metadata=self.metadata)

    def perform(self, **kwargs) -> str:
        operation = kwargs.get("operation", "outage_overview")
        dispatch = {
            "outage_overview": self._outage_overview,
            "crew_dispatch": self._crew_dispatch,
            "customer_comms": self._customer_comms,
            "reliability_reporting": self._reliability_reporting,
        }
        handler = dispatch.get(operation)
        if not handler:
            return f"**Error:** Unknown operation `{operation}`. Available: {', '.join(dispatch)}."
        return handler(**kwargs)

    def _outage_overview(self, **kwargs) -> str:
        """Detect and rank active outages by customer impact and vulnerability

        Article III.4: the default view takes no identifiers — it answers
        "what do I look at today".
        """
        rows = sorted(_records().items(), key=lambda kv: -_pressure(kv[1]))
        breached = [r for r in rows if _days_over(r[1]) > 0]
        L = [f"# Grid Outage Response Agent — {TODAY.isoformat()}\n"]
        L.append(f"**{len(rows)} open outage(s) · {len(breached)} past target**\n")
        L.append("| OTG | " + " | ".join(['circuit', 'cause', 'customers_affected', 'critical_care', 'status', 'crew']) + " | Age | Target | State | Pressure |")
        L.append("|" + "---|" * (6 + 6))
        for rid, r in rows:
            over = _days_over(r)
            state = "BREACHED" if over > 0 else ("AT RISK" if over > -3 else "ON TRACK")
            L.append(f"| {rid} | " + " | ".join(str(r[f]) for f in ['circuit', 'cause', 'customers_affected', 'critical_care', 'status', 'crew'])
                     + f" | {_age(r)}d | {r['target_days']}d | {state}"
                     + (f" (+{over}d)" if over > 0 else "")
                     + f" | {_pressure(r)}/100 |")
        if rows:
            rid, top = rows[0]
            # Article V.1: name the worst offender, or a summarising answer
            # loses the only thing a customer can act on.
            L.append(f"\n## Act on this first\n")
            L.append(f"**{rid}** — {_describe(top)} · {_age(top)} days open against a "
                     f"{top['target_days']}-day target, pressure {_pressure(top)}/100.")
        return "\n".join(L)

    def _crew_dispatch(self, **kwargs) -> str:
        """Dispatch the right crew to the highest-impact circuit first"""
        rid = (kwargs.get("record_id") or "").upper()
        data = _records()
        rows = ([(rid, data[rid])] if rid in data
                else sorted(data.items(), key=lambda kv: -_pressure(kv[1]))[:3])
        if not rows:
            return "No outages match."
        L = ["# Dispatch the right crew to the highest-impact circuit first\n"]
        for rid, r in rows:
            L.append(f"## {rid} — {_describe(r)}\n")
            L.append(f"- Open {_age(r)} days against a {r['target_days']}-day target "
                     f"({'BREACHED by ' + str(_days_over(r)) + 'd' if _days_over(r) > 0 else 'within target'})")
            L.append(f"- Pressure score {_pressure(r)}/100 "
                     f"(severity {r['severity']}/5, {max(0, _days_over(r))} days over)")
            L.append(f"- Recommended: {_next_action(r)}")
            L.append("")
        return "\n".join(L)

    def _customer_comms(self, **kwargs) -> str:
        """Give every affected customer an accurate restoration estimate"""
        rid = (kwargs.get("record_id") or "").upper()
        data = _records()
        rows = ([(rid, data[rid])] if rid in data
                else sorted(data.items(), key=lambda kv: -_pressure(kv[1]))[:3])
        if not rows:
            return "No outages match."
        L = ["# Give every affected customer an accurate restoration estimate\n"]
        for rid, r in rows:
            L.append(f"## {rid} — {_describe(r)}\n")
            L.append(f"- Open {_age(r)} days against a {r['target_days']}-day target "
                     f"({'BREACHED by ' + str(_days_over(r)) + 'd' if _days_over(r) > 0 else 'within target'})")
            L.append(f"- Pressure score {_pressure(r)}/100 "
                     f"(severity {r['severity']}/5, {max(0, _days_over(r))} days over)")
            L.append(f"- Recommended: {_next_action(r)}")
            L.append("")
        return "\n".join(L)

    def _reliability_reporting(self, **kwargs) -> str:
        """Track reliability minutes against the regulator's thresholds continuously"""
        rid = (kwargs.get("record_id") or "").upper()
        data = _records()
        rows = ([(rid, data[rid])] if rid in data
                else sorted(data.items(), key=lambda kv: -_pressure(kv[1]))[:3])
        if not rows:
            return "No outages match."
        L = ["# Track reliability minutes against the regulator's thresholds continuously\n"]
        for rid, r in rows:
            L.append(f"## {rid} — {_describe(r)}\n")
            L.append(f"- Open {_age(r)} days against a {r['target_days']}-day target "
                     f"({'BREACHED by ' + str(_days_over(r)) + 'd' if _days_over(r) > 0 else 'within target'})")
            L.append(f"- Pressure score {_pressure(r)}/100 "
                     f"(severity {r['severity']}/5, {max(0, _days_over(r))} days over)")
            L.append(f"- Recommended: {_next_action(r)}")
            L.append("")
        return "\n".join(L)


if __name__ == "__main__":
    agent = GridOutageResponseAgent()
    for op in ["outage_overview", "crew_dispatch", "customer_comms", "reliability_reporting"]:
        print(agent.perform(operation=op))
        print("\n" + "=" * 78 + "\n")
